### ISSUE TITLE
Setup Storybook and deploy it using GH Pages

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#1]
An example of working storybook: https://github.com/datopian/datapub
Deployed to gh pages: https://datopian.github.io/datapub/

## Acceptance criteria

* [x] I have storybook running here https://datopian.github.io/data-explorer-graphql/ __Done__  https://github.com/datopian/data-explorer-graphql/pull/7

## Tasks

* [x] Setup Storybook with some fixtures for this project
* [x] Deploy to gh pages
