### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#12]
## Tasks

* [x] Fix broken tests @risenW **Done** https://github.com/datopian/data-explorer-graphql/pull/15
* [x] Add tests for Table component @risenW **Done** https://github.com/datopian/data-explorer-graphql/pull/15
* ~~Sort data by date[time] field in a descending order by default so that latest data is visible in the preview~~, see #23  @risenW 
* [x] Move pagination to the bottom of the table @cotts  **Done** #16 
* [x] Remove "Total preview rows" as it isn't so useful, eg, it is always 100 or less @cotts **Done** #16 
* ~~"Total rows" should be updated once filters are applied, eg, it should show the number of filtered rows available~~ see #17 
* [x] Date picker component in the filters
* [x] Rename "filter" button to "submit" 
* [x] Add "reset" button in the filters
* ~~Add "API" button to display a modal with information about generated graphql query~~ see #24  @cotts

**Comment by anuveyatsu** [comment]
FIXED.
