### ISSUE TITLE
Add "Copy query" button

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#24]
The with information about generated graphql query

When I filter dataset, I want to copy/save the query so that I can use it in my app or just in browser to get data from the API.

## Tasks

* [x] Have a look at how it is done currently - check the "Copy API URI" button in the filters component - https://www.energidataservice.dk/tso-electricity/afrrreservesdk1
* [x] Implement "Copy query" button which should be placed in next to "Reset" button

## Analysis

Once the user select a filter, we can get the [Query varialble from here](https://github.com/datopian/data-explorer-graphql/blob/master/src/TableContainer.js#L32) and store in a state to be able to access through components that is [available here](https://github.com/datopian/data-explorer-graphql/blob/master/src/App.js#L7)

If the user reset the filters, the state will be used with the default value.

## Planning work

- [x] Create Buttom Component
- [x] Structure query based on query and organize the state
- [x] Add Copy query to component on click

## Questions

- does the modal should contain a title?
- does the modal should contain some description before or after the query block? 
- does the model should have examples as same as https://www.energidataservice.dk/tso-electricity/afrrreservesdk1 ?

**Comment by anuveyatsu** [comment]
@cotts what I'm interested in right now is how would we do GET request using GraphQL:

https://graphql.org/learn/serving-over-http/#get-request

this way we could avoid having a modal and we could have similar UX as we have currently. However, after quick search I found that Hasura doesn't support GET requests - https://github.com/hasura/graphql-engine/issues/574.
