### ISSUE TITLE
Spinner on load

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#25]
## Acceptance criteria

* [x] I can see the spinner: 
  * [x] while fetching the data for the table preview
  * [x] when paginating and data is being fetched
  * [x] while fetching total number of data rows
  * [x] when filtering data
  * [x] when downloading data

## Tasks

* [x] Check lightweight and minimal spinner
* [x] Display the spinner when loading data via apollo
* [x] Check how file download is implemented and based on that add the spinner

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/data-explorer-graphql/commit/749237fc77cdcb721dbf04349aca7be497f2bac6
