### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#3]
Create a form for building filters for GraphQL queries.

Working example of SQL query builder in production - https://www.energidataservice.dk/tso-electricity/electricitysupplierspergridarea

Source code of the example above: https://github.com/datopian/data-explorer/blob/EDS/src/components/QueryBuilder/QueryBuilder.js

## Acceptance criteria

* [x] I can filter the data by date (`Hour UTC` and `Hour DK` field)  - **DONE**
* [x] I can filter the data by other fields **DONE**- https://github.com/datopian/data-explorer-graphql/blob/quicktest/filter/src/Filter.js#L131
* [x] I can change ordering of the data (see EDS example) **DONE**: https://github.com/datopian/data-explorer-graphql/blob/7ea36efb99a42c6c8149b546df6d7aed3d6603f9/src/Filter.js#L131
* [x] I can see total available rows when filtering **DONE**

## Tasks

* [ ] Brainstorm / check for existing UI/UX for GraphQL filters (would be great to see what else we can build (not just what we've already done in Data Explorer EDS), although we received a great feedback)
* [ ] Create a plan of work here
* [x] create a simple UI ( experimental, but will later be updated ) to test how the filter works **DONE**
* [x] Create input field per schema fields to filter the table data **DONE** - https://github.com/datopian/data-explorer-graphql/blob/7ea36efb99a42c6c8149b546df6d7aed3d6603f9/src/Filter.js#L78
* [x] Generate graphql query base on the input field state **DONE** - https://github.com/datopian/data-explorer-graphql/blob/7ea36efb99a42c6c8149b546df6d7aed3d6603f9/src/Filter.js#L35 
* [x] create `order_by` field to order the table by a field **DONE** - https://github.com/datopian/data-explorer-graphql/blob/7ea36efb99a42c6c8149b546df6d7aed3d6603f9/src/Filter.js#L131

**Comment by steveoni** [comment]
@anuveyatsu I just have a look into the data-api graphql . the `graphql` implementation has the filter process included. What's the way forward on this; are we focusing on the UI/UX first or the functionality at first?

I can self-assign this and start working on it. I just want a heads up on the way forward.

**Comment by anuveyatsu** [comment]
@steveoni yes, we already have GraphQL engine which provides filtering functionality. Here, we are building a UI/UX for it. For example, have a look at how we build filters (based on SQL API) here:

- Energinet project: https://www.energidataservice.dk/tso-electricity/electricitysupplierspergridarea
- National Grid project: https://data.nationalgrideso.com/generation/embedded-wind-and-solar-forecasts/r/embedded_solar_and_wind_forecast

Now, we want to have at least similar UI/UX for building GraphQL filters (queries) instead of SQL. If possible, we want to improve it. To do so, I believe we need to brainstorm / research existing UI/UX in the web (see first task in the task list above). Would you like to start with it?

**Comment by steveoni** [comment]
@anuveyatsu now I get. But from my end, I have a mental model of how the UI/UX functionality will work underneath in relation to how the `filter` controls the `table` view.

I think what I will need to do research on, is what the UI will look like

**Comment by anuveyatsu** [comment]
@steveoni yes, exactly. Could you do that and please have all your notes somewhere in Hackmd (or anything that supports markdown) so we can paste it in this issue?

**Comment by steveoni** [comment]
@anuveyatsu 

## Table filter Analysis

We want to be able to filter and order table contents base on column fields, date. This analysis is to brainstorm an approach using the following reference:
* Energinet project: https://www.energidataservice.dk/tso-electricity/electricitysupplierspergridarea
* National Grid project: https://data.nationalgrideso.com/generation/embedded-wind-and-solar-forecasts/r/embedded_solar_and_wind_forecast

The above links show how to filter tables base on input fields. While Energinet makes use of SQL Builder, our implementation makes use of graphql from `data-api` (https://gitlab.com/datopian/eds/energinet-data-api).

And since the graphql implementation from `data-api` comes with filter and ordering process. Here is how to filter base on fields

```js
........
.filter(where : {ColumnName: {_eq: 'value'}})

```
With this, we can add more filters to the object, like this;
```js
........
.filter(where : {ColumnName1: {_eq: 'value'},
                 ColumName2: {_lt: 'value2'},
                 ColumName3: {_gt: 'value3'}})

```

Using the same UI/UX as the reference shown above, all we need to do is to always add to this object whenever the submit button is clicked. Here is the step by step process:
* Create a `useState` hooks which contain an array of all filter input being created.
* This state hooks enables us to change an input field, delete a field and add new fields.
* And whenever the submit button is created, the state data is formatted  to the way the filter object we look like:  
    ```js 
    {ColumnName1: {_eq: 'value'},
     ColumName2: {_lt: 'value2'},
     ColumName3: {_gt: 'value3'}}
    ```
* This formatted filter data is passed into the filter state, which then updates the table.

To order the table by a column Field, we need to pass the order key to the filter function.

```js
........
filter(order_by: {ColumName: asc})
```
Since table content cal only be ordered by a column field, we need a button to update the filter state with this field.

**NOTE**: Branch https://github.com/datopian/data-explorer-graphql/tree/quicktest/filter contains a quick implementation of the filter process explained here (not including the ordering process).

**Comment by steveoni** [comment]
> @anuveyatsu
> 
> ## Table filter Analysis
> We want to be able to filter and order table contents base on column fields, date. This analysis is to brainstorm an approach using the following reference:
> 
> * Energinet project: https://www.energidataservice.dk/tso-electricity/electricitysupplierspergridarea
> * National Grid project: https://data.nationalgrideso.com/generation/embedded-wind-and-solar-forecasts/r/embedded_solar_and_wind_forecast
> 
> The above links show how to filter tables base on input fields. While Energinet makes use of SQL Builder, our implementation makes use of graphql from `data-api` (https://gitlab.com/datopian/eds/energinet-data-api).
> 
> And since the graphql implementation from `data-api` comes with filter and ordering process. Here is how to filter base on fields
> 
> ```js
> ........
> .filter(where : {ColumnName: {_eq: 'value'}})
> ```
> 
> With this, we can add more filters to the object, like this;
> 
> ```js
> ........
> .filter(where : {ColumnName1: {_eq: 'value'},
>                  ColumName2: {_lt: 'value2'},
>                  ColumName3: {_gt: 'value3'}})
> ```
> 
> Using the same UI/UX as the reference shown above, all we need to do is to always add to this object whenever the submit button is clicked. Here is the step by step process:
> 
> * Create a `useState` hooks which contain an array of all filter input being created.
> * This state hooks enables us to change an input field, delete a field and add new fields.
> * And whenever the submit button is created, the state data is formatted  to the way the filter object we look like:
>   ```js
>   {ColumnName1: {_eq: 'value'},
>    ColumName2: {_lt: 'value2'},
>    ColumName3: {_gt: 'value3'}}
>   ```
> * This formatted filter data is passed into the filter state, which then updates the table.
> 
> To order the table by a column Field, we need to pass the order key to the filter function.
> 
> ```js
> ........
> filter(order_by: {ColumName: asc})
> ```
> 
> Since table content cal only be ordered by a column field, we need a button to update the filter state with this field.
> 
> **NOTE**: Branch https://github.com/datopian/data-explorer-graphql/tree/quicktest/filter contains a quick implementation of the filter process explained here (not including the ordering process).

@anuveyatsu

**Comment by anuveyatsu** [comment]
Some work has been done on generating GraphQL queries here - https://gitlab.com/datopian/eds/energinet-build-report/-/blob/master/src/utils/graphqlUtils.js

**Comment by steveoni** [comment]
@risenW if you are working on this, I have an implementation with design in this branch https://github.com/datopian/data-explorer-graphql/blob/quicktest/filter/src/Filter.js

**Comment by anuveyatsu** [comment]
FIXED in #21
