### ISSUE TITLE
Reset Filter not clear input values 

### ISSUE THREAD

**Issue by cotts** [datopian/data-explorer-graphql#30]
When the reset filter button is clicked, the data stored on the filter object are not well erased.

## Acceptance

* [x] I can click on the reset button and the filters and copy query are set to the default value

## Tasks

* [x] clear filter object  state on click `Reset`
* [x] make sure that all inputs and query are clear

## Analysis

After clicking on Reset Button, the filters are cleared on the view component, but inside the state object, they still remaining if there is only one filter applied.
