### ISSUE TITLE
[UI/UX] Design the data explorer UI and UX

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#38]
## Acceptance Criteria

* [x] I have a nice UX/UI so I can enjoy using the Data Explorer **Done** https://github.com/datopian/data-explorer-graphql/pull/39
* [x] I can use the app without CSS so I can apply my own styles easily
* [x] I can import CSS bundles from here if I'm fine with default styles

<img width="1369" alt="113321436-8037dc80-930b-11eb-8340-b18d54f125ee" src="https://user-images.githubusercontent.com/29900845/113688323-1af43a80-96c1-11eb-9e41-1b57195585f6.png">

## Tasks

UX:

* [x] Brainstorm what should be improved
  * For example, I'm not sure if the way we hide/show filters/tables when data is fetching is great... eg, entire table gets removed and then appears again. As a user, I don't like it because content of the HTML page is also moved up and down and sometimes it's confusing especially when the DataExplorer is just a part of larger page.

* [ ] Check table UX/UI in order to avoid reloading and resize window when click on submit @cotts 

UI:

* [x] Brainstorm / research different applications / projects in the web **Done** We will use ideas from the energi-net explorer, handson table and tabulator
* [x] Create mockups
* [x] Implement mockups @risenW **Done** https://github.com/datopian/data-explorer-graphql/pull/39

## Analysis

Below some UI ideas:

### Tabulator

* http://tabulator.info/

<img width="1298" alt="Screen Shot 2021-04-01 at 9 32 04 AM" src="https://user-images.githubusercontent.com/29900845/113266445-3203e880-92cd-11eb-9b1d-d11dfe3d85cd.png">

### Energinet

* https://www.energidataservice.dk/tso-electricity/electricitysupplierspergridarea

![](https://i.imgur.com/gNHyVzf.png)
![](https://i.imgur.com/nkc18Al.png)

### National Grid

https://data.nationalgrideso.com/demand/14-days-ahead-wind-forecasts/r/14_days_ahead_wind_forecast

<img width="798" alt="Screen Shot 2021-04-01 at 10 07 14" src="https://user-images.githubusercontent.com/17809581/113242137-10f1c680-92d2-11eb-9662-ddb2e35ee069.png">

### Open Data Denmark

https://www.opendata.dk/city-of-copenhagen/cykeldata

<img width="1280" alt="Screen Shot 2021-04-01 at 10 07 46" src="https://user-images.githubusercontent.com/17809581/113242172-24049680-92d2-11eb-95ba-3c91a79d3fd1.png">

### Open Data Montreal

https://donnees.montreal.ca/ville-de-montreal/requetes-entreprises-covid-19

<img width="636" alt="Screen Shot 2021-04-01 at 10 09 32" src="https://user-images.githubusercontent.com/17809581/113242269-6201ba80-92d2-11eb-8dd2-eb90bc183ec6.png">

### Webix
<img width="1110" alt="Screen Shot 2021-04-01 at 9 41 35 AM" src="https://user-images.githubusercontent.com/29900845/113267667-865b9800-92ce-11eb-827b-45ea18d61753.png">

## Handson Table
<img width="881" alt="Screen Shot 2021-04-01 at 9 43 29 AM" src="https://user-images.githubusercontent.com/29900845/113267918-c28ef880-92ce-11eb-9e65-82ba6e64198c.png">

**Comment by anuveyatsu** [comment]
Note that we have Tailwind setup in this project.

**Comment by anuveyatsu** [comment]
@risenW @cotts I've added more examples from existing projects. I'd also suggest exploring ideas outside of Datopian.

**Comment by risenW** [comment]
> @risenW @cotts I've added more examples from existing projects. I'd also suggest exploring ideas outside of Datopian.

Yeah, I got some really nice one, will update the description.

**Comment by anuveyatsu** [comment]
WONTFIX.
