### ISSUE TITLE
Table preview

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#4]
The table component is mostly ready and working. We still need to make sure that data is updating when applying filters and that the data is ordered correctly.

## Acceptance criteria

* [x] I have Table preview of the data that display 100 rows ordered descending, eg, I can see the latest rows
* [x] I have a pagination

## Tasks

* [x] Add Pagination table settings
* [x] Update query to be able to use pagination

TODO

**Comment by cotts** [comment]
@anuveyatsu ,  Should be related at #3 the filter information on the description?
