### ISSUE TITLE
Cross browser compatibility

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#41]
It was reported that the app doesn't work in Firefox, Edge (and probably in Safari) browsers.

## Acceptance criteria

* [x] Works on Firefox
* [x] Works on Edge
* [x] Works on Safari
* [x] Still works on Chrome

Bonus:

* [x] Works on mobile (ios and android):
  * [x] Chrome
  * [x] Firefox
  * [x] Safari

## Tasks

* [x] Reproduce bugs in each browser
* [x] Identify code that isn't supported in the given browser (or identify any other issue causing this)
* [x] Implement fixes

**Comment by risenW** [comment]
FIXED: The app has been tested on all browsers listed above, and it works fine.
