### ISSUE TITLE
Bug when resetting the filters

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#43]
When I reset the filters, the default ordering is also removed.

## Acceptance criteria

* [x] I have default ordering after resetting the filters

## Tasks

* [x] Check how filter is removing ordering query **DONE** : filter is initialized with the date[time] ordering in descending order when the app is mounted, but during reset, the `setFilter` state is set with an empty object
* [x] Apply a fix so that ordering is set to default after reset **DONE**

**Comment by anuveyatsu** [comment]
FIXED.
