### ISSUE TITLE
Unit Test vs Integration Test

### ISSUE THREAD

**Issue by steveoni** [datopian/data-explorer-graphql#45]
Currently `data-explorer-graphql` contains some integration Tests, but whenever there is a bug fix or addition of a feature sometimes it results in some regression (more bug fix).

## Acceptance

- [ ] have an integration test for each feature

## Task

- [x] Using Cypress create tests for:
  - [x] on page load it renders filters, table, pagination, total number of rows
  - [x] filters have date picker for fields with `date` and `datetime` type
  - [x] filtering works, eg, select some filters and submit => table updates with filtered data => total number of rows updates
  - [x] resetting filters => table updates with initial data => total number of rows updates
  - [x] download filtered data in JSON, CSV and XLSX

## Analysis

The Unit testing seems not to catch some of the bugs from implementation details. Some of the components depend on the action from another component; e.g most of the components depend on the `filter` component.

For example for #43 , it's not possible to prevent this by testing the `filter` and the `Table` component separately. But this could have been detected if There is an Integration test, to capture the Table data per filter actions. And also the `Download component` depends on filter action, it will also be good to test how the Download component responds with the filter component

**Comment by tanvirchahal** [comment]
Initial Feedback from Anu: 

- CI for this - can you work on GH Actions so that Cypress tests run on every commit?
- Check the other projects where we have cypress and see what script we use in package.json to run integration tests
- Having WIP pull request would be nice here so I could leave that feedback there

**Comment by tanvirchahal** [comment]
Can we use https://www.npmjs.com/package/cypress-wait-until, to wait for downloads instead of putting in timeouts and wait(3000) commands?

**Comment by anuveyatsu** [comment]
@tanvirchahal I think we can use it for sure.

**Comment by anuveyatsu** [comment]
FIXED.
