### ISSUE TITLE
Integration (cypress) test coverage

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#47]
## Acceptance criteria

* [x] I can understand integration test coverage
* [x] I have a coverage badge with percentage in the README

## Tasks

* [x] Review this doc https://docs.cypress.io/guides/tooling/code-coverage
* [x] Implement in code
* [x] Implment in CI 
* [x] Add the badge in the README

**Comment by anuveyatsu** [comment]
FIXED long time ago.
