### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#5]
Download the data in the preview with no limit (eg, millions of rows) in different formats (CSV, JSON and XLSX).

## Acceptance criteria

* [x] I can download the data in CSV, JSON and XLSX formats.
* ~~I can download millions of rows (only CSV if >1m)~~ this has nothing to do with frontend part.
* [x] I can download filtered data.

## Tasks

* [x] - Add Download Component
* [x] - Add component to table
* [x] Add format select 
* [x] Format query to send to API Route
