### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#50]
At the moment, if something fails, it only shows "error" string without any details:

https://github.com/datopian/data-explorer-graphql/blob/master/src/TableContainer.js#L44
https://github.com/datopian/data-explorer-graphql/blob/845b1dfc00ceb8ff830dc85eddccbbfbece553aa/src/Components/FilterComponents/TotalRows.js#L20-L23

since it is the client-side application and it doesn't log anything to our server, it is difficult to understand why it has failed.

## Acceptance criteria

* [x] I can see descriptive error messages when something fails

## Tasks

* [x] create stories for testing error messages
* [x] parse error object and display it properly

**Comment by anuveyatsu** [comment]
FIXED in #51
