### ISSUE TITLE
Sort by provided primary keys by default

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#52]
The current logic is sorting by the first date[time] column in `desc` order by default:

https://github.com/datopian/data-explorer-graphql/blob/master/src/App.js#L13-L20

Instead of that, we want to sort by provided primary keys in the tableschema. Note that we can have set of primary keys.

## Acceptance criteria

* [x] My data is sorted by provided primary keys in`desc` order by default.

## Tasks

* [x] Implement this new logic
* [ ] Deploy to storybook

**Comment by sagargg** [comment]
This is **DONE**. Commit here
https://github.com/datopian/data-explorer-graphql/commit/301a89e151769403fe34c9db3b3c2246eaf2bfdd
